CFLAGS  = -I/Users/moritzbeckel/Desktop/IDP/src/opt/include -g -Wall
LDFLAGS = -L/Users/moritzbeckel/Desktop/IDP/src/opt/lib
LDLIBS  = -loqs

example_kem:
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ example_kem.c $(LDLIBS)

clean:
	$(RM) example_kem



